export const movieFormFields = [
    {
        key: "title",
        label: "Título",
        type: "text",
        placeholder: "Ingresar título",
        validate: (v) => v.trim() === "" ? "El título es obligatorio" : null,
    },
    {
        key: "genreId",
        label: "Género",
        type: "select",
        placeholder: "Seleccionar género...",
        optionsFrom: "genres",
        validate: (v) => !v ? "Elegí un género" : null,
    },
    {
        key: "synopsis",
        label: "Sinopsis",
        type: "text",
        placeholder: "Breve resumen",
    },
    {
        key: "imageUrl",
        label: "URL Imagen",
        type: "text",
        group: "imageDuration",
    },
    {
        key: "durationMinutes",
        label: "Minutos",
        type: "number",
        group: "imageDuration",
        compact: true,
        validate: (v) => Number(v) <= 0 ? "La duración debe ser mayor a 0" : null,
    },
    {
        key: "suggestedPrice",
        label: "Precio sugerido (opcional)",
        type: "number",
        size: "lg",
        min: 0,
        step: 0.01,
        placeholder: "Precio de referencia para precargar sus funciones",
        omitIfEmpty: true,
        coerce: Number,
        validate: (v) => v !== "" && Number(v) < 0 ? "El precio sugerido no puede ser negativo" : null,
    },
    {
        key: "isActive",
        label: "¿Está en cartelera disponible?",
        type: "checkbox",
    },
];
